class CreateFdicCarryingAmountOfAssetsCoveredByFdicLossShareAgreements < ActiveRecord::Migration[5.1]
  def change
    create_table :fdic_carrying_amount_of_assets_covered_by_fdic_loss_share_agreements do |t|
      t.integer :cert, index: {name: "index_fdic_covered_by_fdic_loss_share_agreements_on_cert"}
      t.integer :docket
      t.integer :fed_rssd
      t.integer :rssdhcr
      t.string :name
      t.string :city
      t.string :stalp
      t.integer :zip
      t.string :repdte
      t.string :rundate
      t.string :bkclass
      t.string :address
      t.string :namehcr
      t.integer :offdom
      t.integer :offfor
      t.integer :stmult
      t.integer :specgrp
      t.integer :subchaps
      t.string :county
      t.integer :cbsa_metro
      t.string :cbsa_metro_name
      t.string :estymd
      t.string :insdate
      t.string :effdate
      t.string :mutual
      t.integer :parcert
      t.integer  :trust
      t.string :regagnt
      t.string :insagnt1
      t.string :fdicdbs
      t.string :fdicsupv
      t.string :fldoff
      t.string :fed
      t.string :occdist
      t.string :otsregnm
      t.integer :offoa
      t.integer :cb
      t.string :inst_webaddr
      t.integer :lsalnls
      t.integer :lrecons
      t.integer :lreag
      t.integer :lreres
      t.integer :lremult
      t.integer :lrenres
      t.integer :lci
      t.integer :lcon
      t.integer :lag
      t.integer :loth
      t.integer :lsaore
      t.integer :loregty
      t.integer :lsascdbt
      t.integer :lsaoa
      t.integer :p3ltot
      t.integer :p3lrecon
      t.integer :p3lreag
      t.integer :p3lreres
      t.integer :p3lremul
      t.integer :p3lrenrs
      t.integer :p3lci
      t.integer :p3lcon
      t.integer :p3lag
      t.integer :p3loth
      t.integer :p3lgty
      t.integer :p9ltot
      t.integer :p9lrecon
      t.integer :p9lreag
      t.integer :p9lreres
      t.integer :p9lremul
      t.integer :p9lrenrs
      t.integer :p9lci
      t.integer :p9lcon
      t.integer :p9lag
      t.integer :p9loth
      t.integer :p9lgty
      t.integer :naltot
      t.integer :nalrecon
      t.integer :nalreag
      t.integer :nalreres
      t.integer :nalremul
      t.integer :nalrenrs
      t.integer :nalci
      t.integer :nalcon
      t.integer :nalag
      t.integer :naloth
      t.integer :nalgty
      t.timestamps
    end
  end
end
