class CreateFdicNetLoansAndLeases < ActiveRecord::Migration[5.1]
  def change
    create_table :fdic_net_loans_and_leases do |t|
      t.integer :cert
      t.integer :docket
      t.integer :fed_rssd
      t.integer :rssdhcr
      t.string :name
      t.string :city
      t.string :stalp
      t.integer :zip
      t.string :repdte
      t.string :rundate
      t.string :bkclass
      t.string :address
      t.string :namehcr
      t.integer :offdom
      t.integer :offfor
      t.integer :stmult
      t.integer :specgrp
      t.integer :subchaps
      t.string :county
      t.integer :cbsa_metro
      t.string :cbsa_metro_name
      t.string :estymd
      t.string :insdate
      t.string :effdate
      t.string :mutual
      t.integer :parcert
      t.integer :trust
      t.string :regagnt
      t.string :insagnt1
      t.string :fdicdbs
      t.string :fdicsupv
      t.string :fldoff
      t.string :fed
      t.string :occdist
      t.string :otsregnm
      t.integer :offoa
      t.integer :cb
      t.string :inst_webaddr
      t.integer :lnlsnet
      t.integer :lnatres
      t.integer :lnlsgr
      t.integer :lncontra
      t.integer :idlnls
      t.integer :lnre
      t.integer :lnredom
      t.integer :lnrecons
      t.integer :lnrenres
      t.integer :lnrenrow
      t.integer :lnrenrot
      t.integer :lnremult
      t.integer :lnreres
      t.integer :lnreag
      t.integer :lnrefor
      t.integer :lnag
      t.integer :lnci
      t.integer :lncinus
      t.integer :lncon
      t.integer :lncrcd
      t.integer :lnconrp
      t.integer :lnauto
      t.integer :lnconoth
      t.integer :lnotci
      t.integer :lnfg
      t.integer :lnmuni
      t.integer :idothlns
      t.integer :ls
      t.integer :lndepac
      t.integer :lncomre
      t.integer :lnrenus
      t.integer :rslnltot
      t.integer :rslnls
      t.integer :lnrecnfm
      t.integer :lnrecnot
      t.integer :rb2lnres
      t.integer :lnlsgrf
      t.timestamps
    end
  end
end
