class CreateFdicAssetsAndLiabilities < ActiveRecord::Migration[5.1]
  def change
    create_table :fdic_assets_and_liabilities do |t|
      t.integer :cert
      t.integer :docket
      t.integer :fed_rssd
      t.integer :rssdhcr
      t.string :name
      t.string :city
      t.string :stalp
      t.integer :zip
      t.string :repdte
      t.string :rundate
      t.string :bkclass
      t.string :address
      t.string :namehcr
      t.integer :offdom
      t.integer :offfor
      t.integer :stmult
      t.integer :specgrp
      t.integer :subchaps
      t.string :county
      t.integer :cbsa_metro
      t.string :cbsa_metro_name
      t.string :estymd
      t.string :insdate
      t.string :effdate
      t.string :mutual
      t.integer :parcert
      t.integer :trust
      t.string :regagnt
      t.string :insagnt1
      t.string :fdicdbs
      t.string :fdicsupv
      t.string :fldoff
      t.string :fed
      t.string :occdist
      t.string :otsregnm
      t.integer :offoa
      t.integer :cb
      t.string :webaddr
      t.integer :numemp
      t.integer :asset
      t.integer :chbal
      t.integer :chbali
      t.integer :sc
      t.integer :frepo
      t.integer :lnlsnet
      t.integer :lnatres
      t.integer :trade
      t.integer :bkprem
      t.integer :ore
      t.integer :intan
      t.integer :idoa
      t.integer :liabeq
      t.integer :liab
      t.integer :dep
      t.integer :depi
      t.integer :depdom
      t.float :iddepinr
      t.integer :frepp
      t.integer :tradel
      t.integer :idobrmtg
      t.integer :subnd
      t.integer :idoliab
      t.integer :eqtot
      t.integer :eq
      t.integer :eqpp
      t.integer :eqcs
      t.integer :eqsur
      t.integer :equptot
      t.integer :eqconsub
      t.integer :nclnls
      t.integer :ncgtypar
      t.integer :oaienc
      t.integer :ernast
      t.integer :asstlt
      t.float :asset5
      t.float :asset2
      t.integer :rwajt
      t.integer :avassetj
      t.integer :oalifins
      t.integer :oalifgen
      t.integer :oalifsep
      t.integer :oalifhyb
      t.integer :voliab
      t.integer :lnexamt
      t.integer :othbfhlb
      t.integer :lnlssale
      t.integer :ucln
      t.integer :rbct1j
      t.integer :rbct2
      t.integer :uc
      t.integer :obsdir,limit: 8
      t.timestamps
    end
  end
end
