class CreateFdicTotalManagedAssetsHeldInFiduciaryAccounts < ActiveRecord::Migration[5.1]
  def change
    create_table :fdic_total_managed_assets_held_in_fiduciary_accounts do |t|
      t.integer :cert
      t.integer :docket
      t.integer :fed_rssd
      t.integer :rssdhcr
      t.string :name
      t.string :city
      t.string :stalp
      t.integer :zip
      t.string :repdte
      t.string :rundate
      t.string :bkclass
      t.string :address
      t.string :namehcr
      t.integer :offdom
      t.integer :offfor
      t.integer :stmult
      t.integer :specgrp
      t.integer :subchaps
      t.string :county
      t.integer :cbsa_metro
      t.string :cbsa_metro_name
      t.string :estymd
      t.string :insdate
      t.string :effdate
      t.string :mutual
      t.integer :parcert
      t.integer :trust
      t.string :regagnt
      t.string :insagnt1
      t.string :fdicdbs
      t.string :fdicsupv
      t.string :fldoff
      t.string :fed
      t.string :occdist
      t.string :otsregnm
      t.integer :offoa
      t.integer :cb
      t.string :inst_webaddr
      t.integer :trpower
      t.integer :trexer
      t.integer :tract
      t.integer :tpimatot
      t.integer :tpini
      t.integer :tpii
      t.integer :tpiscus
      t.integer :tpiscmun
      t.integer :tpimmf
      t.integer :tpieqf
      t.integer :tpiothf
      t.integer :tpitrf
      t.integer :tpisto
      t.integer :tpiothb
      t.integer :tpiuf
      t.integer :tpicps
      t.integer :tpiremtg
      t.integer :tpire
      t.integer :tpimisc
      t.integer :tematot
      t.integer :teni
      t.integer :tei
      t.integer :tescus
      t.integer :tescmun
      t.integer :temmf
      t.integer :teeqf
      t.integer :teothf
      t.integer :tetrf
      t.integer :testo
      t.integer :teothb
      t.integer :teuf
      t.integer :tecps
      t.integer :teremtg
      t.integer :tere
      t.integer :temisc
      t.integer :tomatot
      t.integer :toni
      t.integer :toi
      t.integer :toscus
      t.integer :toscmun
      t.integer :tommf
      t.integer :toeqf
      t.integer :toothf
      t.integer :totrf
      t.integer :tosto
      t.integer :toothb
      t.integer :touf
      t.integer :tocps
      t.integer :toremtg
      t.integer :tore
      t.integer :tomisc
      t.timestamps
    end
  end
end
