class CreateFdicPastDueAndNonaccrualAssets < ActiveRecord::Migration[5.1]
  def change
    create_table :fdic_past_due_and_nonaccrual_assets do |t|
      t.integer :cert
      t.integer :docket
      t.integer :fed_rssd
      t.integer :rssdhcr
      t.string :name
      t.string :city
      t.string :stalp
      t.integer :zip
      t.string :repdte
      t.string :rundate
      t.string :bkclass
      t.string :address
      t.string :namehcr
      t.integer :offdom
      t.integer :offfor
      t.integer :stmult
      t.integer :specgrp
      t.integer :subchaps
      t.string :county
      t.integer :cbsa_metro
      t.string :cbsa_metro_name
      t.string :estymd
      t.string :insdate
      t.string :effdate
      t.string :mutual
      t.integer :parcert
      t.integer :trust
      t.string :regagnt
      t.string :insagnt1
      t.string :fdicdbs
      t.string :fdicsupv
      t.string :fldoff
      t.string :fed
      t.string :occdist
      t.string :otsregnm
      t.integer :offoa
      t.integer :cb
      t.string :inst_webaddr
      t.integer :p3asset
      t.integer :p3re
      t.integer :p3renus
      t.integer :idp3redm
      t.integer :p3recons
      t.integer :p3recnfm
      t.integer :p3recnot
      t.integer :p3reag
      t.integer :p3reres
      t.integer :p3remult
      t.integer :p3renres
      t.integer :p3renrow
      t.integer :p3renrot
      t.integer :p3refor
      t.integer :p3dep
      t.integer :p3depnus
      t.integer :p3ag
      t.integer :p3ci
      t.integer :p3cinus
      t.integer :p3con
      t.integer :p3crcd
      t.integer :p3auto
      t.integer :p3conoth
      t.integer :p3fg
      t.integer :p3othln
      t.integer :p3ls
      t.integer :p3scdebt
      t.integer :p3agsm
      t.integer :p3lnsale
      t.integer :p3gtypar
      t.integer :p3ltot
      t.integer :p9asset
      t.integer :p9re
      t.integer :p9renus
      t.integer :idp9redm
      t.integer :p9recons
      t.integer :p9recnfm
      t.integer :p9recnot
      t.integer :p9reag
      t.integer :p9reres
      t.integer :p9remult
      t.integer :p9renres
      t.integer :p9renrow
      t.integer :p9renrot
      t.integer :p9refor
      t.integer :p9dep
      t.integer :p9depnus
      t.integer :p9ag
      t.integer :p9ci
      t.integer :p9cinus
      t.integer :p9con
      t.integer :p9crcd
      t.integer :p9auto
      t.integer :p9conoth
      t.integer :p9fg
      t.integer :p9othln
      t.integer :p9ls
      t.integer :p9scdebt
      t.integer :p9agsm
      t.integer :p9lnsale
      t.integer :p9gtypar
      t.integer :p9ltot
      t.integer :naasset
      t.integer :nare
      t.integer :narenus
      t.integer :idnaredm
      t.integer :narecons
      t.integer :narecnfm
      t.integer :narecnot
      t.integer :nareag
      t.integer :nareres
      t.integer :naremult
      t.integer :narenres
      t.integer :narenrow
      t.integer :narenrot
      t.integer :narefor
      t.integer :nadep
      t.integer :nadepnus
      t.integer :naag
      t.integer :naci
      t.integer :nacinus
      t.integer :nacon
      t.integer :nacrcd
      t.integer :naauto
      t.integer :naconoth
      t.integer :nafg
      t.integer :naothln
      t.integer :nals
      t.integer :nascdebt
      t.integer :naagsm
      t.integer :nalnsale
      t.integer :nagtypar
      t.integer :naltot
      t.timestamps
    end
  end
end
