class CreateFdicPerformanceAndConditionRatios < ActiveRecord::Migration[5.1]
  def change
    create_table :fdic_performance_and_condition_ratios do |t|
      t.integer :cert
      t.integer :docket
      t.integer :fed_rssd
      t.integer :rssdhcr
      t.string :name
      t.string :city
      t.string :stalp
      t.integer :zip
      t.string :repdte
      t.string :rundate
      t.string :bkclass
      t.string :address
      t.string :namehcr
      t.integer :offdom
      t.integer :offfor
      t.integer :stmult
      t.integer :specgrp
      t.integer :subchaps
      t.string :county
      t.integer :cbsa_metro
      t.string :cbsa_metro_name
      t.string :estymd
      t.string :insdate
      t.string :effdate
      t.string :mutual
      t.integer :parcert
      t.integer :trust
      t.string :regagnt
      t.string :insagnt1
      t.string :fdicdbs
      t.string :fdicsupv
      t.string :fldoff
      t.string :fed
      t.string :occdist
      t.string :otsregnm
      t.integer :offoa
      t.integer :cb
      t.string :webaddr
      t.float :idntilr
      t.float :idntigr
      t.float :intincy
      t.float :intexpy
      t.float :nimy
      t.float :noniiay
      t.float :nonixay
      t.float :elnatry
      t.float :noijy
      t.float :roa
      t.float :roaptx
      t.float :roe
      t.float :roeinjr
      t.float :ntlnlsr
      t.float :elnantr
      t.float :iderncvr
      t.float :eeffr
      t.float :astempm
      t.float :iddivnir
      t.float :ernastr
      t.float :lnatresr
      t.float :lnresncr
      t.float :nperfv
      t.float :nclnlsr
      t.float :lnlsntv
      t.float :lnlsdepr
      t.float :idlncorr
      t.float :depdastr
      t.float :eqv
      t.float :rbc1aaj
      t.float :rbc1rwaj
      t.float :rbcrwaj
      t.float :rbct1cer
      t.float :asset5
      t.float :ernast5
      t.float :eq5
      t.float :lnlsgr5
      t.timestamps
    end
  end
end
