class CreateFdicSecurities < ActiveRecord::Migration[5.1]
  def change
    create_table :fdic_securities do |t|
      t.integer :cert
      t.integer :docket
      t.integer :fed_rssd
      t.integer :rssdhcr
      t.string :name
      t.string :city
      t.string :stalp
      t.integer :zip
      t.string :repdte
      t.string :rundate
      t.string :bkclass
      t.string :address
      t.string :namehcr
      t.integer :offdom
      t.integer :offfor
      t.integer :stmult
      t.integer :specgrp
      t.integer :subchaps
      t.string :county
      t.integer :cbsa_metro
      t.string :cbsa_metro_name
      t.string :estymd
      t.string :insdate
      t.string :effdate
      t.string :mutual
      t.integer :parcert
      t.integer :trust
      t.string :regagnt
      t.string :insagnt1
      t.string :fdicdbs
      t.string :fdicsupv
      t.string :fldoff
      t.string :fed
      t.string :occdist
      t.string :otsregnm
      t.integer :offoa
      t.integer :cb
      t.string :inst_webaddr
      t.integer :sc
      t.integer :scus
      t.integer :scust
      t.integer :scage
      t.integer :scmuni
      t.integer :scdomo
      t.integer :idscod
      t.integer :sccmmb
      t.integer :scabs
      t.integer :scsfp
      t.integer :scodot
      t.integer :scford
      t.integer :sceq
      t.integer :idahta
      t.integer :scres
      t.integer :scpledge
      t.integer :scmtgbk
      t.integer :idscgtpc
      t.integer :scgty
      t.integer :scodpc
      t.integer :idsccmo
      t.integer :sccol
      t.integer :scodpi
      t.integer :idsccmt
      t.integer :sccmpt
      t.integer :sccmot
      t.integer :scha
      t.integer :scaf
      t.integer :scrdebt
      t.integer :scsnhaa
      t.integer :scsnhaf
      t.integer :trade
      t.integer :idtrrval
      t.integer :trlreval
      t.timestamps
    end
  end
end
