class CreateFdicLoansRestructuredInTroubledDebtRestructurings < ActiveRecord::Migration[5.1]
  def change
    create_table :fdic_loans_restructured_in_troubled_debt_restructurings do |t|
      t.integer :cert
      t.integer :docket
      t.integer :fed_rssd
      t.integer :rssdhcr
      t.string :name
      t.string :city
      t.string :stalp
      t.integer :zip
      t.string :repdte
      t.string :rundate
      t.string :bkclass
      t.string :address
      t.string :namehcr
      t.integer :offdom
      t.integer :offfor
      t.integer :stmult
      t.integer :specgrp
      t.integer :subchaps
      t.string :county
      t.integer :cbsa_metro
      t.string :cbsa_metro_name
      t.string :estymd
      t.string :insdate
      t.string :effdate
      t.string :mutual
      t.integer :parcert
      t.integer :trust
      t.string :regagnt
      t.string :insagnt1
      t.string :fdicdbs
      t.string :fdicsupv
      t.string :fldoff
      t.string :fed
      t.string :occdist
      t.string :otsregnm
      t.integer :offoa
      t.integer :cb
      t.string :inst_webaddr
      t.integer :rslnltot
      t.integer :rslnrefm
      t.integer :rslnls
      t.integer :rscons
      t.integer :rsmult
      t.integer :rsnres
      t.integer :rsci
      t.integer :rsother
      t.integer :p3rslnlt
      t.integer :p3rslnfm
      t.integer :p3rslnls
      t.integer :p3rscons
      t.integer :p3rsmult
      t.integer :p3rsnres
      t.integer :p3rsci
      t.integer :p3rsoth
      t.integer :p9rslnlt
      t.integer :p9rslnfm
      t.integer :p9rslnls
      t.integer :p9rscons
      t.integer :p9rsmult
      t.integer :p9rsnres
      t.integer :p9rsci
      t.integer :p9rsoth
      t.integer :narslnlt
      t.integer :narslnfm
      t.integer :narslnls
      t.integer :narscons
      t.integer :narsmult
      t.integer :narsnres
      t.integer :narsci
      t.integer :narsoth
      t.timestamps
    end
  end
end
